[tool.poetry]
name = "find"
version = "0.1.0"
description = ""
authors = ["niuiic <niuiicde@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
